//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realtimesys_datatransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensor_deger_okuma
    {
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.TimeSpan> saat { get; set; }
        public string sensor_adı { get; set; }
        public string sensor_deger { get; set; }
    }
}
